SharePic/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('picture.urls')),
]

# 配置 static 和 media
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

picture/urls.py
from django.urls import path

from . import views

app_name = 'picture'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('picture/picture/', views.PictureAddView.as_view(), name='post_picture_info'),
    path('picture/album/', views.AlbumAddInfoView.as_view(), name='post_album_info'),
    path('reply/info/', views.ReplyAddInfoView.as_view(), name='post_reply_info'),
    path('picture/album/<int:album_id>/', views.AlbumInfoView.as_view(), name='album_info'),
    path('reply/info/<int:reply_id>/', views.ReplyInfoView.as_view(), name='reply_info'),
    path('picture/favorite_album/', views.FavoriteAlbumView.as_view(), name='get_favorite_album'),
    path('picture/like_album/', views.LikeAlbumView.as_view(), name='get_like_album'),
]

user/urls.py
from django.urls import path

from user import views

app_name = 'user'

urlpatterns = [
    # path('register_or_login/', views.RegisterOrLogin.as_view(), name='register_or_login'),
    path('login/', views.MyLoginView.as_view(template_name='user/register_or_login.html'), name='user_login'),
    path('logout/', views.MyLogoutView.as_view(), name='user_logout'),
    path('register/', views.MyRegisterView.as_view(), name='user_register'),
    path('info/<int:user_id>/', views.UserInfoView.as_view(), name="user_info"),
    path('info/', views.MyUserInfoView.as_view(), name='my_user_info'),
    path('exist/', views.CheckUserOrEmailExist.as_view(), name='check_user_exist'),
]

picture/models.py
from itertools import chain
from collections import defaultdict, OrderedDict

from django.db import models
from django.conf import settings

from user.models import User
from SharePic.utils import cache_value

DEFAULT_USER_PICTURE = "/media/user/pictures/default.jpg"


class Picture(models.Model):
    """一张张的图片"""
    picture = models.ImageField(verbose_name="图片")
    desc = models.CharField(max_length=64, default="", verbose_name="描述")
    album_id = models.IntegerField(verbose_name="相册 id", default=0)
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    def __str__(self):
        return self.desc[:10] + "... - %d" % self.id

    class Meta:
        verbose_name = "图片"
        verbose_name_plural = "图片"


class Album(models.Model):
    """相册，他可以关联多张图片"""
    creater_id = models.IntegerField(verbose_name="创建者id", default=0)
    title = models.CharField(max_length=16, verbose_name="相册标题", default="")
    desc = models.CharField(max_length=64, verbose_name="相册描述", default="")
    category = models.IntegerField(verbose_name="种类", default=0)
    tags = models.ManyToManyField('AlbumTag', verbose_name="标签", blank=True)
    first_picture_id = models.IntegerField(verbose_name="第一张图片 id", default=0)
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "相册"
        verbose_name_plural = "相册"

    def to_dict(self, fields=None, exclude=None, ext=True):
        opts = self._meta
        data = {}

        for f in chain(opts.concrete_fields, opts.private_fields, opts.many_to_many):
            if fields and f.name not in fields:
                continue
            if exclude and f.name in exclude:
                continue
            data[f.name] = f.value_from_object(self)

        if ext:
            try:
                user = User.objects.get(id=self.creater_id)
                data["creater__username"] = user.username
                data["creater__picture"] = user.picture.url
            except User.DoseNotExist:
                data["creater__username"] = ""
                data["creater__picture"] = DEFAULT_USER_PICTURE

            data["reviews"] = self.get_reviews()
            data["pictures"] = self.get_pictures()

        return data

    # @cache_value(settings.ALBUM_REVIEWS_CACHE_KEY, "id")
    def get_reviews(self):
        return get_albums_reviews_info(self.id)

    def get_pictures(self):
        data = Picture.objects.filter(album_id=self.id).only("picture")
        return [{"picture": i.picture.url} for i in data]


class AlbumCategory(models.Model):
    """相册分类"""
    name = models.CharField(max_length=16, verbose_name="分类名", default="")
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    def __str__(self):
        return "%d - %s" % (self.id, self.name)

    class Meta:
        verbose_name = "相册分类"
        verbose_name_plural = "相册分类"


class AlbumTag(models.Model):
    """相册标签"""
    name = models.CharField(max_length=16, verbose_name="标签名", default="")
    update_time = models.DateTimeField(auto_now=True, verbose_name="更新时间")

    def __str__(self):
        return "%d - %s" % (self.id, self.name)

    class Meta:
        verbose_name = "相册标签"
        verbose_name_plural = "相册标签"


class Reply(models.Model):
    """回复相册或图片"""
    creater_id = models.IntegerField(verbose_name="创建者", default=0)
    album_id = models.IntegerField(verbose_name="相册id", default=0)
    picture_id = models.IntegerField(verbose_name="图片id", default=0)
    parent_reply = models.IntegerField(verbose_name="回复的回复id")
    content = models.CharField(max_length=128, verbose_name="内容", default="")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    def __str__(self):
        return "%d - %s..." % (self.creater_id, self.content[:10])

    class Meta:
        verbose_name = "图片回复"
        verbose_name_plural = "图片回复"


class FavoriteAlbum(models.Model):
    album_id = models.IntegerField(verbose_name="相册id", default=0)
    creater_id = models.IntegerField(verbose_name="收藏人id", default=0)
    creater_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    def __str__(self):
        return "%d - %d" % (self.album_id, self.creater_id)

    class Meta:
        verbose_name = "收藏"
        verbose_name_plural = "收藏"


class LikeAlbum(models.Model):
    album_id = models.IntegerField(verbose_name="相册id", default=0)
    creater_id = models.IntegerField(verbose_name="点赞人id", default=0)
    creater_time = models.DateTimeField(auto_now_add=True, verbose_name="创建时间")

    def __str__(self):
        return "%d - %d" % (self.album_id, self.creater_id)

    class Meta:
        verbose_name = "点赞"
        verbose_name_plural = "点赞"


def get_field_username_id_map(kclass, ids, field):
    usernames = kclass.objects.filter(id__in=ids).values("id", field)
    return {u["id"]: u[field] for u in usernames}


def get_field_info_id_map(kclass, ids, *field):
    usernames = kclass.objects.filter(id__in=ids).values("id", *field)
    return {u["id"]: u for u in usernames}


def get_albums_reviews_info(album_id):
    # 传入相册id，获取相册的回复信息
    replies = (
        Reply.objects.filter(album_id=album_id)
        .order_by("-id")
        .values(
            "id", "album_id", "parent_reply", "content", "creater_id", "create_time"
        )
    )
    creater_ids = list(set([rep["creater_id"] for rep in replies]))
    user_id_name_map = get_field_info_id_map(User, creater_ids, "username", "picture")

    first_replies = OrderedDict()
    second_replies = defaultdict(list)
    for rep in replies:
        user_info = user_id_name_map.get(rep["creater_id"])
        rep["creater__username"] = user_info["username"] if "username" in user_info and user_info["username"] else ""
        rep["creater__picture"] = settings.MEDIA_URL + user_info["picture"] if "picture" in user_info and user_info["picture"] else DEFAULT_USER_PICTURE

        if rep["parent_reply"] == 0:
            first_replies[rep["id"]] = rep
        else:
            second_replies[rep["parent_reply"]].append(rep)

    for k in first_replies:
        first_replies[k]["replies"] = second_replies.get(k, [])

    return list(first_replies.values())

picture/forms.py
from django.forms import ModelForm

from .models import Reply
from SharePic.middleware import get_request_user_id


class AddReplyInfoFrom(ModelForm):
    
    def save(self, commit=True):
        user_id = get_request_user_id()
        self.instance.creater_id = user_id
        return super(AddReplyInfoFrom, self).save()
    
    class Meta:
        model = Reply
        fields = ["parent_reply", "album_id", "content"]

picture/views.py
import time

from django.shortcuts import render
from django.views.generic.base import TemplateView, View
from django.core.paginator import Paginator
from django.db.models.query_utils import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy as reverse
from django.http import JsonResponse, Http404

from .models import Picture, Album, FavoriteAlbum, LikeAlbum
from .utils import extend_albums_count, update_favorite_album_count, extend_album_info, update_like_album_count, update_reply_album_count
from .forms import AddReplyInfoFrom


class IndexView(LoginRequiredMixin, TemplateView):
    login_url = reverse('user:user_login')
    template_name = "picture/index.html"

    def get_page(self):
        # 获取分页器
        page_no = int(self.request.GET.get("page_no", 1) or 1)
        page_size = int(self.request.GET.get("page_size", 18) or 18)
        if page_size > 50:
            page_size = 18

        return Paginator(self.get_queryset(), page_size).get_page(page_no)

    def get_context_data(self, **kwargs):

        page = self.get_page()
        albums = page.object_list
        values = albums.values("id", "create_time", "title", "desc", "creater_id", "first_picture_id")
        if values:
            extend_albums_count(values, self.request.user.id)  # 扩展收藏数、回复数、用户名、第一张图片

        kwargs["values"] = values
        kwargs["page"] = page
        kwargs["q"] = self.request.GET.get("q", "")

        return kwargs

    def get_queryset(self):
        # 获取查询集
        q = self.request.GET.get("q", "")
        if q:
            return Album.objects.filter(Q(desc__contains=q) | Q(title__contains=q)).order_by("-id")
        return Album.objects.all().order_by("-id")


class AlbumInfoView(LoginRequiredMixin, View):
    login_url = reverse('user:user_login')

    def get(self, request, album_id, *args, **kwargs):
        # 相冊詳情
        try:
            album_info = Album.objects.get(id=album_id)
        except Album.DoesNotExist:
            return Http404("沒有改相冊。")

        di = album_info.to_dict(("id", "title", "desc", "creater_id", "create_time"))
        extend_album_info(di, request.user.id)

        return render(request, 'picture/get_album_info.html', di)

    def put(self, request, album_id, *args, **kwargs):
        return JsonResponse({"code": 0, "msg": "成功", "data": "暂未开发"})

    def delete(self, request, album_id, *args, **kwargs):
        return JsonResponse({"code": 0, "msg": "成功", "data": "暂未开发"})


class AlbumAddInfoView(LoginRequiredMixin, View):
    login_url = reverse('user:user_login')

    def post(self, request, *args, **kwargs):
        print(request.POST)
        title = request.POST.get("title", "")
        desc = request.POST.get("desc", "")
        picture_ids = request.POST.get("picture_ids", "")
        if not desc:
            return JsonResponse({"code": 101, "msg": "缺少 desc", "data": {"id": -1}})
        if not picture_ids:
            return JsonResponse({"code": 101, "msg": "缺少 pictures", "data": {"id": -1}})

        picture_ids = picture_ids.split(",")
        obj = Album.objects.create(
            title=title, desc=desc, first_picture_id=picture_ids[0], creater_id=request.user.id
        )
        Picture.objects.filter(id__in=picture_ids).update(album_id=obj.id)

        return JsonResponse({"code": 0, "msg": "成功", "data": {"id": obj.id}})


class PictureAddView(LoginRequiredMixin, View):
    login_url = reverse('user:user_login')

    def post(self, request, *args, **kwargs):
        files = request.FILES.getlist("file")
        pictures = []
        for f in files:
            obj = Picture.objects.create(picture=f)
            pictures.append({"id": obj.id, "picture_url": obj.picture.url})

        return JsonResponse({"code": 0, "msg": "成功", "data": pictures})


class ReplyInfoView(LoginRequiredMixin, View):
    login_url = reverse('user:user_login')

    def get(self, request, reply_id, *args, **kwargs):
        return JsonResponse({"code": 0, "msg": "成功", "data": "暂未开发"})

    def put(self, request, reply_id, *args, **kwargs):
        return JsonResponse({"code": 0, "msg": "成功", "data": "暂未开发"})

    def delete(self, request, reply_id, *args, **kwargs):
        return JsonResponse({"code": 0, "msg": "成功", "data": "暂未开发"})


class ReplyAddInfoView(LoginRequiredMixin, View):
    login_url = reverse('user:user_login')

    def post(self, request, *args, **kwargs):
        form = AddReplyInfoFrom(request.POST)
        if form.is_valid():
            obj = form.save()
            update_reply_album_count(obj.album_id)
            return JsonResponse({"code": 0, "msg": "成功", "data": {"id": obj.id}})
        return JsonResponse({"code": 400, "msg": "验证失败", "data": form.errors})


class FavoriteAlbumView(LoginRequiredMixin, View):
    login_url = reverse('user:user_login')

    def get(self, request, *args, **kwargs):
        # 添加、删除收藏文章
        album_id = request.GET.get("album_id")
        obj_id = -1

        if not album_id:
            return JsonResponse({"code": 101, 'msg': '缺少 album_id'})

        if FavoriteAlbum.objects.filter(album_id=album_id, creater_id=request.user.id).count() > 0:
            FavoriteAlbum.objects.filter(album_id=album_id, creater_id=request.user.id).delete()
        else:
            obj_id = FavoriteAlbum.objects.create(album_id=album_id, creater_id=request.user.id).id
        update_favorite_album_count(album_id)

        return JsonResponse({'code': 0, 'msg': '成功', 'data': {'id': obj_id}})


class LikeAlbumView(LoginRequiredMixin, View):
    login_url = reverse('user:user_login')

    def get(self, request, *args, **kwargs):
        # 添加、删除收藏文章
        album_id = request.GET.get("album_id")
        obj_id = -1

        if not album_id:
            return JsonResponse({"code": 101, 'msg': '缺少 album_id'})

        if LikeAlbum.objects.filter(album_id=album_id, creater_id=request.user.id).count() > 0:
            LikeAlbum.objects.filter(album_id=album_id, creater_id=request.user.id).delete()
        else:
            obj_id = LikeAlbum.objects.create(album_id=album_id, creater_id=request.user.id).id
        update_like_album_count(album_id)

        return JsonResponse({'code': 0, 'msg': '成功', 'data': {'id': obj_id}})

templates/default/picture/index.html
{% extends 'base.html' %}

{% load datetime_filters %}

{% block script %}
    <script>
        $(function () {
            var $heart = $(".heart");

            $heart.click(function(){
                // 点击收藏切换图标颜色
                id = $(this).attr("id");
                $.ajax({
                    url: "{% url 'picture:get_favorite_album' %}" + "?album_id=" + id,
                    type: 'GET',
                    success: function(data, status, xhr){
                        if (data.code == 0) {
                            toggle_heart_color(id);
                        }
                    }
                })
            });

            var toggle_heart_color = function(id) {
                // 切换收藏图标颜色
                $current = $("#" + id);
                var $heart_n_span = $current.parent().next();
                var heart_count = parseInt($heart_n_span.text());
                if ($current.css("color") == "rgb(232, 94, 146)"){
                    $heart_n_span.html(heart_count - 1);
                    $current.css("color", "rgb(128, 128, 128)");
                } else {
                    $heart_n_span.html(heart_count + 1);
                    $current.css("color", "rgb(232, 94, 146)");
                }
            };

            function change_div3_height_eq_width(){
				var glo_height = 0;
                $(".img-cover").each(function(){
                    wid = $(this).css("width");
                    <!--pad_left = $(this).parent().css("padding-left");-->
                    <!--pad_right = $(this).parent().css("padding-right");-->
                    if (Math.abs(parseInt(wid)-glo_height) > 1){
                    	glo_height = parseInt(wid);
                    }
                    height = glo_height + "px";

                    $(this).css("height", height);
                })
            }
            change_div3_height_eq_width();
            $(window).resize(change_div3_height_eq_width);
        })
    </script>
{% endblock %}

{% block style %}
    <style>
        body {
            background-color: #b4daf1;
        }
        .heart {
            font-size: 16px;
        }
        .reply {
            font-size: 16px;
            color: green;
        }
        .heart_span {
            font-size: 16px;
        }
        .img-cover {
            width:100%;
            object-fit: cover;
        }

        a:link{text-decoration:none;   /* 指正常的未被访问过的链接*/}
        a:visited{text-decoration:none; /*指已经访问过的链接*/}
        a:hover{text-decoration:none;/*指鼠标在链接*/}
        a:active{text-decoration:none;/* 指正在点的链接*/ }

    </style>
{% endblock %}

{% block title %}share life index{% endblock %}

{% block body %}
    <!--<div class="container-fluid" style="padding-left:23px;padding-right:23px;background-color:#f0f2f1;padding-top:10px;">-->
    <div class="container" style="padding-left:23px;padding-right:23px;background-color:#f0f2f1;padding-top:10px;">

        <div class="row">

            {% for value in values %}
            <div class="col-lg-2 col-md-3 col-sm-6 col-xs-12" style="padding-left:8px;padding-right:8px;padding-top:8px;padding-bottom:8px">
                <div class="thumbnail" style="margin-bottom:0px;">
                    <a href="{% url 'picture:album_info' value.id %}"><img class="img-cover" src="{{ value.first_picture }}" alt="..."></a>
                    <div class="caption">
                        <!--<a href="http://baidu.com/s?wd=穷怎么办" class="text-danger" style="font-size:16px;">校花图</a>-->
                        <a href="{% url 'user:user_info' value.creater_id %}" class="text-danger">{{ value.user__username }}</a>
                        <p class="text-muted" style="margin-top:5px;margin-bottom:5px;font-size:12px;">{{ value.create_time|datetime_semantization }}</p>
                        <p style="font-size:13px;height:36px;">{{ value.desc|limit_str_len:90 }}</p>
                    </div>
                    <div style="background-color:#e2e6e4;margin-left:-4px;margin-right:-4px;margin-bottom:-4px;text-indent:6px;line-height:34px;">
                        <a href="javascript:">
                            {% if value.is_favorite %}
                            <span title="点击收藏" style="color:rgb(232, 94, 146);" class="glyphicon glyphicon-heart heart initialism" aria-hidden="true" id="{{ value.id }}"></span>
                            {% else %}
                            <span title="点击收藏" style="color:gray;" class="glyphicon glyphicon-heart heart initialism" aria-hidden="true" id="{{ value.id }}"></span>
                            {% endif %}
                        </a>
                        <span class="heart_span">{{ value.favorite_count }}</span>
                        <a href="javascript:"> <span class="glyphicon glyphicon-comment reply" aria-hidden="true"></span></a>
                        <span class="heart_span">{{ value.reply_count }}</span>
                    </div>
                </div>
            </div>

            {% endfor %}
        </div>
    </div>

    <!--分页-->
    <nav aria-label="Page navigation" style="text-align:center;">
        <ul class="pagination pagination-lg">
            {% if page.number == 1 %}
            <li class="disabled"><a href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
            {% else %}
            <li><a href="{% url 'picture:index' %}?q={{ q }}&page_no={{ page.number|add:-1 }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
            {% endif %}

            {% for i in page.paginator.page_range %}
            {% if i == page.number %}<li class="active">{% else %}<li>{% endif %}
                <a href="{% url 'picture:index' %}?q={{ q }}&page_no={{ i }}">{{ i }}</a>
            </li>
            {% endfor %}

            {% if page.has_next %}<li><a href="{% url 'picture:index' %}?q={{ q }}&page_no={{i|add:-1}}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
            {% else %}
            <li class="disabled"><a href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
            </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}